"""BAGEL training packer package."""

from .anchors import (
    BAGEL_DUMMY_ANCHORS_META_KEY,
    add_dummy_anchor_to_batch,
    append_dummy_anchor,
    dummy_anchors_from_conversation,
    fold_dummy_anchors,
    zero_hidden_from_batch,
)
from .carrier import (
    BAGEL_PACKED_BATCH_META_KEY,
    BAGEL_TRAIN_LABEL_IDS,
    clear_packed_batch,
    conversation_samples,
    get_packed_batch,
    packed_label_rows,
    require_packed_batch,
    set_packed_batch,
)
from .item_layout import (
    BAGEL_TRAIN_CE_INDEXES,
    BAGEL_TRAIN_HIDDEN_STATES,
    BAGEL_TRAIN_LABEL_IDS,
    BAGEL_TRAIN_LAYOUT_PLANNED,
    BAGEL_TRAIN_MSE_TARGET,
    assemble_training_forward,
    collect_ce_loss_inputs,
    collect_mse_loss_inputs,
    collect_training_text_ids,
    ensure_training_layout_planned,
    materialize_training_text_ids,
    patchified_clean_latents,
    prepare_flow_training_metadata,
    scatter_training_hidden_states,
    scatter_training_text_embeds,
    training_layout_planned,
)
from .packing import BagelTrainingPacker, pack_training_conversation


__all__ = [
    "BAGEL_TRAIN_CE_INDEXES",
    "BAGEL_TRAIN_HIDDEN_STATES",
    "BAGEL_TRAIN_LABEL_IDS",
    "BAGEL_TRAIN_LAYOUT_PLANNED",
    "BAGEL_TRAIN_MSE_TARGET",
    "BAGEL_DUMMY_ANCHORS_META_KEY",
    "BAGEL_PACKED_BATCH_META_KEY",
    "BagelTrainingPacker",
    "add_dummy_anchor_to_batch",
    "append_dummy_anchor",
    "assemble_training_forward",
    "clear_packed_batch",
    "collect_ce_loss_inputs",
    "collect_mse_loss_inputs",
    "collect_training_text_ids",
    "conversation_samples",
    "dummy_anchors_from_conversation",
    "ensure_training_layout_planned",
    "fold_dummy_anchors",
    "get_packed_batch",
    "materialize_training_text_ids",
    "pack_training_conversation",
    "packed_label_rows",
    "patchified_clean_latents",
    "prepare_flow_training_metadata",
    "require_packed_batch",
    "scatter_training_hidden_states",
    "scatter_training_text_embeds",
    "set_packed_batch",
    "training_layout_planned",
    "zero_hidden_from_batch",
]
