janus_siglip:
  model_path: janus_siglip
  accelerator:
    fsdp_config:
      fsdp_mode: eager
janus_vqvae:
  model_path: janus_vqvae
  accelerator:
    gradient_checkpointing:
      enable: false
janus_text_encoder:
  model_path: janus_text_encoder
  accelerator:
    gradient_checkpointing:
      enable: false
janus_llama:
  model_path: janus_llama
