janus_siglip:
  model:
    model_path: janus_siglip

  accelerator:
    fsdp_config:
      fsdp_mode: eager

janus_vqvae:
  model:
    model_path: janus_vqvae

  accelerator:
    fsdp_config:
      fsdp_mode: ddp

janus_text_encoder:
  model:
    model_path: janus_text_encoder

  accelerator:
    fsdp_config:
      fsdp_mode: fsdp2
    extra_parallel_sizes: [4]
    extra_parallel_names: ["emb"]
    extra_parallel_placement_innermost: [false]

janus_llama:
  model:
    model_path: janus_llama

  accelerator:
    fsdp_config:
      fsdp_mode: fsdp2
