janus_siglip:
  model:
    model_path: janus_siglip

janus_vqvae:
  model:
    model_path: janus_vqvae

    ops_implementation:
      attn_implementation: eager

janus_text_encoder:
  model:
    model_path: janus_text_encoder

janus_llama:
  model:
    model_path: janus_llama
    ops_implementation:
      attn_implementation: flash_attention_2

  accelerator:
    fsdp_config:
      fsdp_mode: fsdp2
