janus_siglip:
  model_path: janus_siglip
  accelerator:
    fsdp_config:
      fsdp_mode: eager
janus_vqvae:
  model_path: janus_vqvae
janus_text_encoder:
  model_path: janus_text_encoder
janus_llama:
  model_path: janus_llama
