---
title: veomni_janus — infer_gen
---
%%{init: {'flowchart': {'defaultRenderer': 'elk'}}}%%
flowchart LR
    fsm_start(("▶")):::fsm_start
    fsm_done(("⏹")):::fsm_terminal
    subgraph state_prompt_encode [prompt_encode]
        direction LR
        prompt_encode__siglip_generate["siglip_generate<br/><i>janus_siglip.generate</i>"]:::body_node
        prompt_encode__janus_llama_gen["janus_llama_gen<br/><i>janus_llama.generate</i>"]:::body_node
        prompt_encode__tok_encode_generate["tok_encode_generate<br/><i>janus_text_encoder.generate</i>"]:::body_node
        prompt_encode__siglip_generate -->|"conversation_list"| prompt_encode__janus_llama_gen
        prompt_encode__tok_encode_generate -->|"conversation_list"| prompt_encode__janus_llama_gen
    end
    subgraph state_image_vq_start [image_vq_start]
        direction LR
        image_vq_start__emit_image_start["emit_image_start<br/><i>janus_text_encoder.emit_image_start</i>"]:::body_node
    end
    subgraph state_image_vq [image_vq]
        direction LR
        image_vq__janus_llama_gen["janus_llama_gen<br/><i>janus_llama.generate</i>"]:::body_node
        image_vq__vae_generate["vae_generate<br/><i>janus_vqvae.generate</i>"]:::body_node
        image_vq__janus_llama_gen -->|"hidden_states"| image_vq__vae_generate
        image_vq__vae_generate -->|"conversation_list"| image_vq__janus_llama_gen
    end
    subgraph state_image_vq_end [image_vq_end]
        direction LR
        image_vq_end__emit_image_end["emit_image_end<br/><i>janus_text_encoder.emit_image_end</i>"]:::body_node
    end
    state_prompt_encode -.-> state_prompt_encode
    state_image_vq_start -.-> state_image_vq_start
    state_image_vq -.-> state_image_vq
    state_image_vq_end -.-> state_image_vq_end
    fsm_start ==> state_prompt_encode
    state_prompt_encode ==>|"default"| state_image_vq_start
    state_image_vq_start ==>|"default"| state_image_vq
    state_image_vq ==>|"module_signal(image_complete)"| state_image_vq_end
    state_image_vq_end ==>|"default"| fsm_done
    classDef body_node fill:#fff,stroke:#666
    classDef fsm_start fill:#dff,stroke:#06c,stroke-width:2px
    classDef fsm_terminal fill:#eee,stroke:#333,stroke-width:1px,stroke-dasharray:3 3
    style state_prompt_encode fill:#eef,stroke:#06c,stroke-width:2px
