model:
  model_path: ../models/gemma-3-12b-it
  ops_implementation:
    attn_implementation: sdpa
    rms_norm_implementation: npu
    rotary_pos_emb_implementation: npu
    swiglu_mlp_implementation: eager
    cross_entropy_loss_implementation: npu

data:
  train_path: ../data/tulu-first2000.parquet
  data_type: conversation
  chat_template: chatml
  max_seq_len: 8192
  train_size: 750000
  text_keys: messages
  dyn_bsz_buffer_size: 2000

train:
  dyn_bsz: true
  accelerator:
    ulysses_size: 1
    fsdp_config:
      fsdp_mode: fsdp2
      mixed_precision:
        enable: true
    offload:
      enable_activation: false
  gradient_checkpointing:
    enable: true
  global_batch_size: 8
  micro_batch_size: 1
  bsz_warmup_ratio: 0.0
  optimizer:
    type: adamw
    lr: 1.0e-4
    lr_decay_style: cosine
    max_grad_norm: 1.0
  num_train_epochs: 10
  init_device: meta
  empty_cache_steps: 500
  checkpoint:
    output_dir: gemma-3-12b-sft-tulu-npu
    manager: dcp
    save_steps: 100000
    save_epochs: 10000
    save_hf_weights: true
  wandb:
    project: VeOmni
    name: gemma-3-12b-sft-tulu-npu
