"""Core model-contract and discovery helpers for the parity suite."""

from .compare import (
    MetricResult,
    ParityReport,
    ProbeReport,
    Tolerance,
    compare_tensors,
    compare_values,
    tolerance_from_policy,
)
from .config import (
    DEFAULT_GATE,
    PARITY_ENABLE_ENV,
    GateSpec,
    GraphSpec,
    LauncherSpec,
    ModelSpec,
    NodeSpec,
    ParityCase,
    ProbeCatalog,
    ProbeMapping,
    RecipeSpec,
    ReferenceSpec,
    RefTapSpec,
    ResolvedProbes,
    RunSpec,
    V2GradSpec,
    case_skip_reason,
    discover_cases,
    discover_graph_specs,
    discover_nodes,
    load_model_spec,
    load_probe_catalog,
    resolve_probes,
)
from .fixtures import make_reference_image
from .runtime import (
    autocast_for_dtype,
    configure_torch_determinism,
    patched_randn_like,
    resolve_torch_dtype,
    sample_grad,
    sample_named_grad,
    sum_losses,
    to_cpu,
    to_device,
    zero_module_grads,
)


__all__ = [
    "DEFAULT_GATE",
    "GateSpec",
    "GraphSpec",
    "LauncherSpec",
    "ModelSpec",
    "NodeSpec",
    "PARITY_ENABLE_ENV",
    "ParityCase",
    "ParityReport",
    "MetricResult",
    "ProbeCatalog",
    "ProbeReport",
    "ProbeMapping",
    "RecipeSpec",
    "ReferenceSpec",
    "RefTapSpec",
    "ResolvedProbes",
    "RunSpec",
    "Tolerance",
    "V2GradSpec",
    "autocast_for_dtype",
    "case_skip_reason",
    "configure_torch_determinism",
    "compare_tensors",
    "compare_values",
    "discover_cases",
    "discover_graph_specs",
    "discover_nodes",
    "load_model_spec",
    "load_probe_catalog",
    "make_reference_image",
    "patched_randn_like",
    "resolve_torch_dtype",
    "sample_grad",
    "sample_named_grad",
    "resolve_probes",
    "sum_losses",
    "to_cpu",
    "to_device",
    "tolerance_from_policy",
    "zero_module_grads",
]
