"""Core model-contract and discovery helpers for the parity suite."""

from .compare import (
    MetricResult,
    ParityReport,
    ProbeReport,
    Tolerance,
    compare_tensors,
    compare_values,
    tolerance_from_policy,
)
from .config import (
    DEFAULT_GATE,
    PARITY_ENABLE_ENV,
    GateSpec,
    GraphSpec,
    HfModelReferenceSpec,
    LauncherSpec,
    ModelSpec,
    NodeSpec,
    ParityCase,
    ProbeCatalog,
    ProbeMapping,
    RecipeSpec,
    RecipeV2ModelSpec,
    ReferenceSpec,
    RefTapSpec,
    ResolvedProbes,
    RunSpec,
    V2GradSpec,
    V2ModelSpec,
    V2ModelTargetSpec,
    case_skip_reason,
    discover_cases,
    discover_graph_specs,
    discover_nodes,
    effective_reference_kind,
    load_model_spec,
    load_probe_catalog,
    resolve_probes,
    select_v2_model_target,
)
from .fixtures import make_reference_image
from .runtime import (
    RunCaptureOptions,
    RunWorkerOptions,
    autocast_for_dtype,
    configure_torch_determinism,
    patched_randn_like,
    resolve_torch_dtype,
    run_capture_context,
    run_runtime_context,
    run_worker_context,
    sample_grad,
    sample_named_grad,
    sample_named_param,
    sample_tensor,
    sum_losses,
    to_cpu,
    to_device,
    zero_module_grads,
)
from .selectors import apply_v2_selector, reference_probe_values, v2_probe_values
from .stimulus import (
    CONVERSATION_ITEM_TYPES,
    CONVERSATION_VALUE_KINDS,
    conversation_stimulus_to_batched_specs,
    validate_stimulus,
)


__all__ = [
    # Config and discovery
    "DEFAULT_GATE",
    "GateSpec",
    "GraphSpec",
    "HfModelReferenceSpec",
    "LauncherSpec",
    "ModelSpec",
    "NodeSpec",
    "PARITY_ENABLE_ENV",
    "ParityCase",
    "ProbeCatalog",
    "ProbeMapping",
    "RecipeSpec",
    "RecipeV2ModelSpec",
    "ReferenceSpec",
    "RefTapSpec",
    "ResolvedProbes",
    "RunSpec",
    "V2GradSpec",
    "V2ModelSpec",
    "V2ModelTargetSpec",
    "case_skip_reason",
    "discover_cases",
    "discover_graph_specs",
    "discover_nodes",
    "effective_reference_kind",
    "load_model_spec",
    "load_probe_catalog",
    "resolve_probes",
    "select_v2_model_target",
    # Comparison and reports
    "MetricResult",
    "ParityReport",
    "ProbeReport",
    "Tolerance",
    "compare_tensors",
    "compare_values",
    "tolerance_from_policy",
    # Probe value selection
    "apply_v2_selector",
    "reference_probe_values",
    "v2_probe_values",
    # Fixtures
    "make_reference_image",
    # Stimulus
    "CONVERSATION_ITEM_TYPES",
    "CONVERSATION_VALUE_KINDS",
    "conversation_stimulus_to_batched_specs",
    "validate_stimulus",
    # Runtime helpers
    "RunCaptureOptions",
    "RunWorkerOptions",
    "autocast_for_dtype",
    "configure_torch_determinism",
    "patched_randn_like",
    "resolve_torch_dtype",
    "run_capture_context",
    "run_runtime_context",
    "run_worker_context",
    "sample_grad",
    "sample_named_grad",
    "sample_named_param",
    "sample_tensor",
    "sum_losses",
    "to_cpu",
    "to_device",
    "zero_module_grads",
]
