bagel_vae:
  model_path: bagel_vae
  model_config:
    support_cache: true
bagel_siglip_navit:
  model_path: bagel_siglip_navit
bagel_text_encoder:
  model_path: bagel_text_encoder
bagel_flow_connector:
  model_path: bagel_flow_connector
bagel_qwen2_mot:
  model_path: bagel_qwen2_mot
