bagel_vae:
  model_path: bagel_vae
  accelerator:
    fsdp_config:
      fsdp_mode: fsdp2
bagel_siglip_navit:
  model_path: bagel_siglip_navit
  accelerator:
    fsdp_config:
      fsdp_mode: fsdp2
bagel_text_encoder:
  model_path: bagel_text_encoder
  accelerator:
    fsdp_config:
      fsdp_mode: fsdp2
bagel_flow_connector:
  model_path: bagel_flow_connector
  accelerator:
    fsdp_config:
      fsdp_mode: fsdp2
bagel_qwen2_mot:
  model_path: bagel_qwen2_mot
  accelerator:
    fsdp_config:
      fsdp_mode: fsdp2
