bagel_text_encoder:
  model:
    model_path: bagel_text_encoder

bagel_siglip_navit:
  model:
    model_path: bagel_siglip_navit

bagel_vae:
  model:
    model_path: bagel_vae

bagel_flow_connector:
  model:
    model_path: bagel_flow_connector

bagel_qwen2_mot:
  model:
    model_path: bagel_qwen2_mot
