"""SeedOmni V2 native inference — one launcher YAML, one prompt, one optional image.

Usage
-----
::

    # Text → image (no image arg means infer_gen scenario)
    python tasks/infer/infer_omni.py \\
        configs/seed_omni/janus_1.3b/veomni_janus.yaml \\
        --model.model_path /tmp/janus_1.3b_split \\
        --infer.prompt "A close-up of Sydney Opera House at night."

    # Image + text → text  (image arg implies infer_und scenario)
    python tasks/infer/infer_omni.py \\
        configs/seed_omni/janus_1.3b/veomni_janus.yaml \\
        --infer.prompt "Describe this image." \\
        --infer.image path/or/url.png

CLI surface
-----------
The launcher YAML is consumed as the positional ``config_file`` argument
(same convention as ``tasks/train_omni.py``).  Every value declared in
the YAML is overridable via ``--section.field`` flags
auto-generated by :func:`veomni.arguments.parse_args` from the dataclass
tree below:

* ``--model.model_path PATH`` — override the launcher YAML's
  ``model.model_path`` (typically the split-checkpoint root produced by
  ``scripts/multimodal/convert_model/split_janus.py``).
* ``--model.omni_infer_type {infer_gen,infer_und,infer_interleave}`` —
  force a specific inference scenario.  If unset, the scenario is
  auto-picked from whether ``--infer.image`` was supplied (image
  present → ``infer_und``, absent → ``infer_gen``).
* ``--infer.prompt TEXT`` — user prompt (required).
* ``--infer.image PATH|URL`` — optional image for I2T scenarios.
* ``--infer.output_dir DIR`` — where ``reply.txt`` /
  ``generated_image_*.png`` / ``trace.txt`` land (default: ``output``).
* ``--infer.guidance_scale FLOAT`` — Janus CFG weight (default 5.0,
  ignored for I2T and when ≤ 1.0).
* ``--infer.max_tokens INT`` — FSM iteration cap (default 1024).
* ``--infer.seed INT`` / ``--infer.temperature FLOAT`` /
  ``--infer.top_p FLOAT`` — standard sampling knobs inherited from
  :class:`veomni.arguments.InferArguments`.
* ``--infer.trace`` — dump FSM step/transition log to
  ``<output_dir>/trace.txt``.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field

import requests
import torch
from PIL import Image

from veomni.arguments import InferArguments, parse_args
from veomni.trainer.omni_inferencer import OmniInferencer, OmniInferModelArguments


# ── Argument dataclasses ─────────────────────────────────────────────────────


@dataclass
class OmniInferArguments(InferArguments):
    """Inference knobs for ``infer_omni`` — extends framework ``InferArguments``.

    Inherited and used: ``seed``, ``temperature``, ``top_p``, ``max_tokens``,
    ``do_sample``.

    Inherited and silently ignored: ``model_path`` / ``tokenizer_path``.
    The V2 entry-point sources the model from the launcher YAML's
    ``model:`` section via :class:`OmniModelArguments`, so ``--model.model_path``
    is the canonical override.  These two fields are overridden here to
    have a default of ``None`` (the base class declares ``model_path`` as
    mandatory) and are documented as "ignored" so users don't reach for
    the wrong flag.
    """

    model_path: str | None = field(
        default=None,
        metadata={"help": "Ignored — use --model.model_path to override the launcher YAML."},
    )
    tokenizer_path: str | None = field(
        default=None,
        metadata={"help": "Ignored — tokenizer is loaded from --model.model_path (the split-ckpt root)."},
    )
    prompt: str = field(
        default="",
        metadata={"help": "User text prompt (required; non-empty)."},
    )
    image: str | None = field(
        default=None,
        metadata={"help": "Optional path or http(s) URL to an image.  Omit for text-to-image generation."},
    )
    output_dir: str = field(
        default="output",
        metadata={"help": "Directory for reply.txt + generated_image_*.png + trace.txt (created if missing)."},
    )
    guidance_scale: float = field(
        default=5.0,
        metadata={
            "help": (
                "Classifier-free guidance weight for text-to-image generation (Janus default = 5.0). "
                "Ignored for I2T scenarios and when ≤ 1.0.  Same shape as the HF baseline "
                "`scripts/multimodal/infer/janus_hf_infer_gen.py`."
            )
        },
    )
    trace: bool = field(
        default=False,
        metadata={"help": "Dump FSM step / transition log to <output_dir>/trace.txt (debugging aid)."},
    )

    def __post_init__(self):
        # Base-class __post_init__ tries `self.tokenizer_path = self.model_path`
        # when tokenizer_path is None.  That's harmless when both are None
        # (which is the V2 case), but we skip the super call to make the
        # "both ignored" semantics explicit and avoid mutating an unused
        # field.
        pass


@dataclass
class Arguments:
    """Root config for ``infer_omni`` — consumed by :func:`parse_args`.

    The launcher YAML's top-level ``model:`` section populates :attr:`model`,
    keeping only the four fields that actually drive inference (model path +
    graph YAML pointers).  ``data:`` / ``train:`` and every other
    training-only ``model.*`` field declared in the launcher YAML
    (``ops_implementation``, ``encoders``, ``lora_config``, ...) are silently
    ignored because they're not declared on :class:`OmniInferModelArguments`.
    """

    model: OmniInferModelArguments = field(default_factory=OmniInferModelArguments)
    infer: OmniInferArguments = field(default_factory=OmniInferArguments)


# ── Helpers ──────────────────────────────────────────────────────────────────


def _load_image(path: str) -> Image.Image:
    if path.startswith(("http://", "https://")):
        return Image.open(requests.get(path, stream=True).raw).convert("RGB")
    if not os.path.exists(path):
        raise FileNotFoundError(f"Image path does not exist: {path}")
    return Image.open(path).convert("RGB")


def _save_image(tensor: torch.Tensor, out_path: str) -> None:
    """Save a ``(1, H, W, 3)`` or ``(H, W, 3)`` tensor in ``[-1, 1]`` as PNG."""
    img = tensor.detach().to(dtype=torch.float32, device="cpu")
    if img.dim() == 4 and img.size(0) == 1:
        img = img.squeeze(0)
    if img.dim() != 3 or img.size(-1) != 3:
        raise ValueError(f"Cannot save image with shape {tuple(img.shape)} (expected (H, W, 3)).")
    arr = ((img.clamp(-1.0, 1.0) + 1.0) * 127.5).round().to(torch.uint8).numpy()
    Image.fromarray(arr).save(out_path)


def _extract_reply(ctx: dict) -> str:
    finalize = ctx.get("finalize") or {}
    for payload in finalize.values():
        if isinstance(payload, dict) and "text" in payload:
            return payload["text"]
    return ""


def _select_scenario(model_args: OmniInferModelArguments, *, has_image: bool) -> tuple[str, str]:
    """Pick the inference scenario (an entry in ``model.omni_infer_yaml_path``).

    Priority:

    1. ``model.omni_infer_type`` if set (via CLI ``--model.omni_infer_type`` or YAML).
       An unknown value raises ``KeyError`` — silently falling through to auto-pick
       would mask typos (e.g. ``--model.omni_infer_type infrr_gen``) that the user
       would otherwise want to catch immediately.
    2. Auto: image present → ``infer_und``, absent → ``infer_gen``.
    3. Any scenario declared in ``omni_infer_yaml_path`` (first key).

    Returns
    -------
    ``(scenario, source)`` where ``source`` is one of ``"yaml/cli"`` /
    ``"auto"`` / ``"fallback"`` — the caller prints this so users can tell
    which priority path fired (especially important since the launcher YAML
    may declare ``omni_infer_type`` for training-time generation samples,
    which now also applies to inference).
    """
    infer_map = dict(model_args.omni_infer_yaml_path or {})
    if not infer_map:
        raise ValueError(
            "Launcher YAML declares no `model.omni_infer_yaml_path` entries — cannot pick an inference scenario."
        )
    if model_args.omni_infer_type:
        if model_args.omni_infer_type not in infer_map:
            known = ", ".join(sorted(infer_map)) or "(none)"
            raise KeyError(
                f"Unknown model.omni_infer_type {model_args.omni_infer_type!r}; expected one of: {known}.  "
                f"Set via CLI: --model.omni_infer_type <key>."
            )
        return model_args.omni_infer_type, "yaml/cli (model.omni_infer_type)"
    preferred = "infer_und" if has_image else "infer_gen"
    if preferred in infer_map:
        return preferred, f"auto (has_image={has_image})"
    return next(iter(infer_map)), "fallback (first available)"


# ── Main ─────────────────────────────────────────────────────────────────────


def main() -> None:
    args = parse_args(Arguments)

    if not args.infer.prompt:
        raise ValueError("`--infer.prompt` is required (use a non-empty string).  Example: --infer.prompt 'a cat'.")
    if not args.model.model_path:
        raise ValueError("`--model.model_path` is required (launcher YAML must declare `model.model_path`).")

    has_image = bool(args.infer.image)
    force_image_gen = not has_image  # T2I scenarios steer to image-VQ immediately
    scenario, scenario_source = _select_scenario(args.model, has_image=has_image)

    print(f"[infer_omni] model_path      = {args.model.model_path}")
    print(f"[infer_omni] scenario        = {scenario}  (source: {scenario_source})")

    os.makedirs(args.infer.output_dir, exist_ok=True)

    cfg = args.model.load_omni_config(infer_type=scenario)
    inferencer = OmniInferencer(cfg, seed=args.infer.seed)

    images: list[Image.Image] = [_load_image(args.infer.image)] if has_image else []

    # CFG only kicks in for T2I — for I2T we squelch back to 1.0 so the
    # janus_text_encoder skips the uncond branch (its construction rule
    # isn't well-defined for prompts containing image_und parts; see
    # `_maybe_build_cfg_uncond_embeds`).
    guidance_scale = float(args.infer.guidance_scale) if force_image_gen else 1.0
    generation_kwargs = {
        "temperature": args.infer.temperature,
        "top_p": args.infer.top_p,
        "do_sample": args.infer.do_sample,
        "guidance_scale": guidance_scale,
    }

    trace_buf: list[str] = [] if args.infer.trace else None
    ctx = inferencer.generate(
        prompt=args.infer.prompt,
        images=images,
        force_image_gen=force_image_gen,
        generation_kwargs=generation_kwargs,
        max_new_tokens=args.infer.max_tokens,
        trace=trace_buf,
    )

    reply = _extract_reply(ctx)
    reply_path = os.path.join(args.infer.output_dir, "reply.txt")
    # encoding="utf-8" is load-bearing — Janus is multilingual so reply text
    # may carry CJK / emoji.  Default-locale opens crash on `LANG=C` images.
    with open(reply_path, "w", encoding="utf-8") as f:
        f.write(reply + ("\n" if reply and not reply.endswith("\n") else ""))
    print(f"[infer_omni] reply ({len(reply)} chars) → {reply_path}")
    if reply:
        print(f"--- reply ---\n{reply}\n-------------")

    images_out: list[torch.Tensor] = list(ctx.get("generated_images_collected") or [])
    for idx, img_tensor in enumerate(images_out):
        out_path = os.path.join(args.infer.output_dir, f"generated_image_{idx}.png")
        _save_image(img_tensor, out_path)
        print(f"[infer_omni] image #{idx} → {out_path}")

    if trace_buf is not None:
        trace_path = os.path.join(args.infer.output_dir, "trace.txt")
        with open(trace_path, "w", encoding="utf-8") as f:
            f.write("\n".join(trace_buf) + "\n")
        print(f"[infer_omni] FSM trace ({len(trace_buf)} lines) → {trace_path}")

    if not reply and not images_out:
        print("[infer_omni] WARNING — FSM produced no reply and no images.")


if __name__ == "__main__":
    main()
