"""SeedOmni V2 native inference — one launcher YAML, one prompt, one optional image.

Usage
-----
::

    # Text → image
    python tasks/infer/infer_omni.py \\
        configs/seed_omni/janus_1.3b/veomni_janus.yaml \\
        --infer.model_path /tmp/janus_1.3b_split \\
        --model.omni_infer_type infer_gen \\
        --infer.prompt "A close-up of Sydney Opera House at night."

    # Image + text → text
    python tasks/infer/infer_omni.py \\
        configs/seed_omni/janus_1.3b/veomni_janus.yaml \\
        --infer.model_path /tmp/janus_1.3b_split \\
        --model.omni_infer_type infer_und \\
        --infer.prompt "Describe this image." \\
        --infer.image path/or/url.png

CLI surface
-----------
The launcher YAML is the positional ``config_file`` argument (same
convention as ``tasks/train_omni.py``).  All argument / setup logic lives
in :mod:`veomni.trainer.omni_inferencer` — this entry-point is a thin
driver.  Every field declared on :class:`OmniInferenceArguments` is
overridable via ``--section.field`` flags auto-generated by
:func:`veomni.arguments.parse_args`:

* ``--infer.model_path PATH`` — split-checkpoint root (produced by
  ``scripts/multimodal/convert_model/split_janus.py``).  Auto-mirrored
  onto ``model.model_path`` / ``model.tokenizer_path``.
* ``--model.omni_infer_type {infer_gen,infer_und,infer_interleave}`` —
  active scenario key into ``model.omni_infer_yaml_path`` (required).
* ``--infer.prompt TEXT`` — user prompt (required, non-empty).
* ``--infer.image PATH|URL`` — image input for I2T scenarios.
* ``--infer.output_dir DIR`` — root output directory (default ``output``);
  artefacts land under ``<output_dir>/<omni_infer_type>/``.
* ``--infer.guidance_scale FLOAT`` — Janus CFG weight for T2I (default 5.0,
  squelched to 1.0 for I2T).
* ``--infer.max_tokens INT`` — FSM iteration cap (default 1024).
* ``--infer.seed`` / ``--infer.temperature`` / ``--infer.top_p`` —
  sampling knobs inherited from :class:`veomni.arguments.InferArguments`.
* ``--infer.trace`` — dump FSM step / transition log to
  ``<output_dir>/trace.txt``.
"""

from __future__ import annotations

from veomni.arguments import parse_args
from veomni.trainer.omni_inferencer import OmniInferenceArguments, OmniInferencer


def main() -> None:
    args = parse_args(OmniInferenceArguments)
    inferencer = OmniInferencer(args)
    inferencer.generate()


if __name__ == "__main__":
    main()
