"""SeedOmni V2 native inference — one launcher YAML, one prompt, one optional image.

Usage
-----
::

    # Text → image (no image arg means infer_gen scenario)
    python tasks/infer/infer_omni.py \\
        configs/seed_omni/janus_1.3b/veomni_janus.yaml \\
        --model.model_path /tmp/janus_1.3b_split \\
        --infer.prompt "A close-up of Sydney Opera House at night."

    # Image + text → text  (image arg implies infer_und scenario)
    python tasks/infer/infer_omni.py \\
        configs/seed_omni/janus_1.3b/veomni_janus.yaml \\
        --infer.prompt "Describe this image." \\
        --infer.image path/or/url.png

CLI surface
-----------
The launcher YAML is consumed as the positional ``config_file`` argument
(same convention as ``tasks/train_omni.py``).  All argument / setup logic
lives in :mod:`veomni.trainer.omni_inferencer` so this entry-point is
intentionally a 3-line driver — every value declared in the launcher YAML
is overridable via ``--section.field`` flags auto-generated by
:func:`veomni.arguments.parse_args` from the dataclasses on
:class:`OmniInferenceArguments`:

* ``--model.model_path PATH`` — override the launcher YAML's
  ``model.model_path`` (typically the split-checkpoint root produced by
  ``scripts/multimodal/convert_model/split_janus.py``).
* ``--model.omni_infer_type {infer_gen,infer_und,infer_interleave}`` —
  force a specific inference scenario.  If unset, the scenario is
  auto-picked from whether ``--infer.image`` was supplied (image
  present → ``infer_und``, absent → ``infer_gen``).
* ``--infer.prompt TEXT`` — user prompt (required).
* ``--infer.image PATH|URL`` — optional image for I2T scenarios.
* ``--infer.output_dir DIR`` — root output directory.  The resolved
  scenario is joined onto this path, so the actual artefacts land under
  ``<output_dir>/<omni_infer_type>/`` (e.g. ``output/infer_gen/`` for T2I,
  ``output/infer_und/`` for I2T).  Default ``output``.
* ``--infer.guidance_scale FLOAT`` — Janus CFG weight (default 5.0,
  ignored for I2T and when ≤ 1.0).
* ``--infer.max_tokens INT`` — FSM iteration cap (default 1024).
* ``--infer.seed INT`` / ``--infer.temperature FLOAT`` /
  ``--infer.top_p FLOAT`` — standard sampling knobs inherited from
  :class:`veomni.arguments.InferArguments`.
* ``--infer.trace`` — dump FSM step/transition log to
  ``<output_dir>/trace.txt``.
"""

from __future__ import annotations

from veomni.arguments import parse_args
from veomni.trainer.omni_inferencer import OmniInferenceArguments, OmniInferencer


def main() -> None:
    args = parse_args(OmniInferenceArguments)
    OmniInferencer.from_args(args).generate()


if __name__ == "__main__":
    main()
