model:
  model_path: Wan-AI/Wan2.1-I2V-1.3B-diffusers
  lora_config:
    rank: 128
    alpha: 64
    lora_modules: q,k,v,o,ffn.0,ffn.2

data:
  train_path: /mnt/hdfs/user_dir/seedance/dataset/avengers
  train_size: 1000000000000
  max_seq_len: 8192
  source_name: video_generation_demo
  mm_configs:
    fps: 24

train:
  output_dir: Wan2.1-I2V-1.3B_lora
  data_parallel_mode: fsdp1
  ulysses_parallel_size: 1
  global_batch_size: 8
  micro_batch_size: 1
  bsz_warmup_ratio: 0.007
  dyn_bsz: false
  optimizer: adamw
  lr: 1.0e-4
  lr_warmup_ratio: 0.007
  lr_decay_style: constant
  lr_decay_ratio: 1.0
  weight_decay: 0.01
  max_grad_norm: 1.0
  init_device: cuda
  max_steps: 20
  num_train_epochs: 1
  save_hf_weights: true
  use_wandb: true
  wandb_project: veomni_dit
  wandb_name: Wan2.1-I2V-1.3B_lora
  training_task: online_training
