# Copyright 2026 Bytedance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Versioned HunyuanImage 3 resolution policy (model-local).

The anchor/ratio table is generated by exactly reproducing Tencent's
``ResolutionGroup`` from ``tokenization_hunyuan_image_3.py`` /
``image_processor.py`` at revision ``6e9113a692a27a0751d82aba3b2015a876646c03``:
``align=16``, ``step=base_size // 16`` and the four extra resolutions the
official ``HunyuanImage3ImageProcessor`` adds for the ``1024`` anchor. A bucket
must map exactly to an existing Base ``<img_size_*>`` / ``<img_ratio_*>`` token,
so a custom policy may only select or reweight generated buckets -- never add an
anchor or ratio that lacks a Base token.

This module owns the deterministic HI3 bucket table + the HI3-specific weight
derivation. Selection semantics (the pure-function per-step scheduler, the
dataset indexer, the same-bucket batch sampler) live in the model-agnostic
``veomni.data.bucket`` package; the ``build_bucket_*`` factory helpers below
wire the two together.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Callable, Literal, Optional

from ....data.bucket import BucketBatchSampler, BucketIndexer, BucketScheduler


if TYPE_CHECKING:
    import numpy as np


RESOLUTION_POLICY_PRESET = "hunyuan_image_3_official_v1"
_ALIGN = 16
# The official image_processor adds these to the base_size=1024 vae_reso_group.
_OFFICIAL_EXTRA_RESOLUTIONS_1024 = ((1024, 768), (1280, 720), (768, 1024), (720, 1280))
_SUPPORTED_ANCHORS = (256, 512, 1024)


@dataclass(frozen=True)
class ResolutionBucket:
    """One selectable bucket: pixel shape, latent/token grid, and Base tokens."""

    bucket_id: int
    base_size: int
    ratio_index: int
    height: int
    width: int
    latent_height: int
    latent_width: int
    token_height: int
    token_width: int

    @property
    def grid_hw(self) -> tuple[int, int]:
        """The compiler image grid (latent grid divided by the patch size)."""
        return self.token_height, self.token_width


@dataclass
class ResolutionAnchorConfig:
    base_size: int
    ratio_indices: list[int] = field(default_factory=list)  # Empty means the anchor's full table.
    ratio_weights: dict[int, float] = field(default_factory=dict)  # Omitted entries default to 1.0.
    weight: float = 1.0  # Anchor-level multiplier.


@dataclass
class ResolutionPolicyConfig:
    preset: Literal["hunyuan_image_3_official_v1"] = RESOLUTION_POLICY_PRESET
    anchors: list[ResolutionAnchorConfig] = field(default_factory=list)  # Empty means every preset anchor.
    selection_mode: Literal["synchronized_weighted", "synchronized_curriculum"] = "synchronized_weighted"
    scheduler_seed: int = 0
    insufficient_bucket_policy: Literal["drop_insufficient_bucket", "deterministic_replacement"] = (
        "drop_insufficient_bucket"
    )

    def __post_init__(self):
        # The shared argument parser does not recurse into ``list[T]`` dataclass
        # elements, so normalize YAML anchor dictionaries here (mirrors the RFC).
        self.anchors = [
            ResolutionAnchorConfig(**anchor) if isinstance(anchor, dict) else anchor for anchor in self.anchors
        ]
        if not all(isinstance(anchor, ResolutionAnchorConfig) for anchor in self.anchors):
            raise TypeError("anchors must contain ResolutionAnchorConfig objects or dictionaries")
        if self.preset != RESOLUTION_POLICY_PRESET:
            raise ValueError(f"Unsupported resolution policy preset: {self.preset!r}.")


def _calc_resolutions_by_step(base_size: int, step: int, align: int) -> list[tuple[int, int]]:
    """Reproduce Tencent ``ResolutionGroup._calc_by_step`` (height, width order)."""
    if base_size % align:
        raise ValueError(f"base_size {base_size} is not divisible by align {align}.")
    if align > step:
        raise ValueError(f"align {align} must not exceed step {step}.")

    min_height = min_width = base_size // 2
    max_height = max_width = base_size * 2

    resolutions = [(base_size, base_size)]

    cur_height, cur_width = base_size, base_size
    while not (cur_height >= max_height and cur_width <= min_width):
        cur_height = min(cur_height + step, max_height)
        cur_width = max(cur_width - step, min_width)
        resolutions.append((cur_height // align * align, cur_width // align * align))

    cur_height, cur_width = base_size, base_size
    while not (cur_height <= min_height and cur_width >= max_width):
        cur_height = max(cur_height - step, min_height)
        cur_width = min(cur_width + step, max_width)
        resolutions.append((cur_height // align * align, cur_width // align * align))

    return sorted(resolutions, key=lambda hw: hw[0] / hw[1])


def _resolutions_for_anchor(base_size: int) -> list[tuple[int, int]]:
    """Generate one anchor's official resolution table, with extras deduped by ratio."""
    resolutions = _calc_resolutions_by_step(base_size, step=base_size // _ALIGN, align=_ALIGN)
    if base_size == 1024:
        existing_ratios = {height / width for height, width in resolutions}
        for height, width in _OFFICIAL_EXTRA_RESOLUTIONS_1024:
            ratio = height / width
            if ratio not in existing_ratios:
                resolutions.append((height, width))
                existing_ratios.add(ratio)
    return resolutions


class HunyuanImage3ResolutionPolicy:
    """Expanded, deterministic bucket table with official-compatible selection."""

    def __init__(self, config: ResolutionPolicyConfig, *, vae_spatial_factor: int = 16, patch_size: int = 1):
        self.config = config
        self.vae_spatial_factor = vae_spatial_factor
        self.patch_size = patch_size
        self._anchor_ratios: dict[int, list[float]] = {}
        self._buckets: list[ResolutionBucket] = []
        self._buckets_by_key: dict[tuple[int, int], ResolutionBucket] = {}

        selected_anchors = config.anchors or [
            ResolutionAnchorConfig(base_size=anchor) for anchor in _SUPPORTED_ANCHORS
        ]
        bucket_id = 0
        for anchor in selected_anchors:
            if anchor.base_size not in _SUPPORTED_ANCHORS:
                raise ValueError(f"Anchor base_size {anchor.base_size} has no Base <img_size_*> token.")
            resolutions = _resolutions_for_anchor(anchor.base_size)
            self._anchor_ratios[anchor.base_size] = [height / width for height, width in resolutions]
            ratio_indices = anchor.ratio_indices or list(range(len(resolutions)))
            for ratio_index in ratio_indices:
                if not 0 <= ratio_index < len(resolutions):
                    raise ValueError(f"ratio_index {ratio_index} is outside anchor {anchor.base_size}'s Base table.")
                height, width = resolutions[ratio_index]
                bucket = self._build_bucket(bucket_id, anchor.base_size, ratio_index, height, width)
                self._buckets.append(bucket)
                self._buckets_by_key[(anchor.base_size, ratio_index)] = bucket
                bucket_id += 1

    def _build_bucket(self, bucket_id, base_size, ratio_index, height, width) -> ResolutionBucket:
        factor = self.vae_spatial_factor
        if height % factor or width % factor:
            raise ValueError(f"Bucket {height}x{width} is not divisible by the VAE factor {factor}.")
        latent_height, latent_width = height // factor, width // factor
        if latent_height % self.patch_size or latent_width % self.patch_size:
            raise ValueError(f"Latent grid {latent_height}x{latent_width} is not divisible by patch_size.")
        return ResolutionBucket(
            bucket_id=bucket_id,
            base_size=base_size,
            ratio_index=ratio_index,
            height=height,
            width=width,
            latent_height=latent_height,
            latent_width=latent_width,
            token_height=latent_height // self.patch_size,
            token_width=latent_width // self.patch_size,
        )

    @property
    def buckets(self) -> list[ResolutionBucket]:
        return list(self._buckets)

    @property
    def all_bucket_ids(self) -> list[int]:
        """Every bucket id in the policy -- passed to the generic ``BucketBatchSampler``."""
        return [bucket.bucket_id for bucket in self._buckets]

    @property
    def bucket_labels(self) -> dict[int, str]:
        """Human-readable ``bucket_id -> label`` for log lines (drop warnings, etc.)."""
        return {
            bucket.bucket_id: f"{bucket.height}x{bucket.width} base={bucket.base_size} ratio_index={bucket.ratio_index}"
            for bucket in self._buckets
        }

    def select_bucket(self, *, width: int, height: int, base_size: int) -> ResolutionBucket:
        """Map a raw ``W x H`` to the nearest ratio bucket of ``base_size``.

        Reproduces the official ``get_base_size_and_ratio_index``: nearest ratio
        by absolute difference (first index wins on ties, matching ``np.argmin``).
        """
        if base_size not in self._anchor_ratios:
            raise ValueError(f"Anchor base_size {base_size} is not active in this policy.")
        ratios = self._anchor_ratios[base_size]
        target_ratio = height / width
        ratio_index = min(range(len(ratios)), key=lambda index: abs(ratios[index] - target_ratio))
        if (base_size, ratio_index) not in self._buckets_by_key:
            raise ValueError(f"Ratio index {ratio_index} for base_size {base_size} is disabled by this policy.")
        return self._buckets_by_key[(base_size, ratio_index)]

    def compute_bucket_weights(self) -> dict[int, float]:
        """Derive the ``bucket_id -> weight`` map from the anchor / ratio config.

        Each anchor contributes ``anchor.weight * anchor.ratio_weights.get(ratio_index,
        1.0)`` to its own buckets. Anchors not listed in ``config.anchors`` (i.e.
        preset defaults selected implicitly) contribute weight 1.0. Validation
        of positivity is deferred to :class:`BucketScheduler`, which rejects
        non-positive weights at construction.
        """
        anchor_by_base = {anchor.base_size: anchor for anchor in self.config.anchors}
        weights: dict[int, float] = {}
        for bucket in self._buckets:
            anchor = anchor_by_base.get(bucket.base_size)
            if anchor is None:
                weight = 1.0
            else:
                weight = float(anchor.weight) * float(anchor.ratio_weights.get(bucket.ratio_index, 1.0))
            weights[bucket.bucket_id] = weight
        return weights

    def policy_hash(self) -> str:
        """Stable BLAKE2b of the full HI3 bucket table (geometry + ordering).

        Consumed by :class:`BucketIndexer`'s fingerprint so a resume across a
        geometry change (bucket added / removed / reshaped) is rejected at
        checkpoint reload.
        """
        table = [
            [
                bucket.bucket_id,
                bucket.base_size,
                bucket.ratio_index,
                bucket.height,
                bucket.width,
                bucket.token_height,
                bucket.token_width,
            ]
            for bucket in self._buckets
        ]
        payload = json.dumps({"table": table}, separators=(",", ":"), sort_keys=True).encode("utf-8")
        return hashlib.blake2b(payload, digest_size=16).hexdigest()


def build_resolution_policy(
    config: Optional[ResolutionPolicyConfig] = None,
    *,
    vae_spatial_factor: int = 16,
    patch_size: int = 1,
) -> HunyuanImage3ResolutionPolicy:
    return HunyuanImage3ResolutionPolicy(
        config or ResolutionPolicyConfig(),
        vae_spatial_factor=vae_spatial_factor,
        patch_size=patch_size,
    )


# ----------------------------------------------------------------------------
# Factory helpers -- wire the generic bucket primitives to this policy.
# ----------------------------------------------------------------------------


def build_hunyuan_image_3_bucket_scheduler(policy: HunyuanImage3ResolutionPolicy) -> BucketScheduler:
    """Construct a :class:`BucketScheduler` from the HI3 resolution policy.

    Only ``synchronized_weighted`` is supported today; ``synchronized_curriculum``
    is reserved until its schema is frozen and raises ``NotImplementedError``.
    """
    config = policy.config
    if config.selection_mode == "synchronized_curriculum":
        raise NotImplementedError(
            "synchronized_curriculum bucket selection is not implemented yet; "
            "use selection_mode='synchronized_weighted'."
        )
    if config.selection_mode != "synchronized_weighted":
        raise ValueError(f"Unsupported bucket selection_mode: {config.selection_mode!r}.")
    return BucketScheduler(
        weights=policy.compute_bucket_weights(),
        scheduler_seed=int(config.scheduler_seed),
    )


def build_hunyuan_image_3_bucket_indexer(
    policy: HunyuanImage3ResolutionPolicy,
    *,
    default_base_size: int,
    width_key: str = "width",
    height_key: str = "height",
    image_key: str = "image",
) -> BucketIndexer:
    """Construct a :class:`BucketIndexer` bound to this policy's ``default_base_size``.

    Validates ``default_base_size`` up-front so a mistyped YAML entry fails
    loud at build time instead of misclassifying every sample.
    """
    if not isinstance(default_base_size, int) or isinstance(default_base_size, bool):
        raise TypeError("default_base_size must be an int.")
    if default_base_size <= 0:
        raise ValueError("default_base_size must be positive.")
    base_sizes = {bucket.base_size for bucket in policy.buckets}
    if default_base_size not in base_sizes:
        raise ValueError(
            f"default_base_size={default_base_size} is not present in the resolution policy "
            f"(active base sizes: {sorted(base_sizes)}). Adjust "
            f"``data.image_generation.default_base_size`` or ``resolution_policy.anchors``."
        )

    def _bucket_of(width: int, height: int) -> int:
        return int(policy.select_bucket(width=int(width), height=int(height), base_size=default_base_size).bucket_id)

    return BucketIndexer(
        bucket_of=_bucket_of,
        policy_fingerprint=policy.policy_hash(),
        width_key=width_key,
        height_key=height_key,
        image_key=image_key,
    )


def build_hunyuan_image_3_bucket_batch_sampler(
    policy: HunyuanImage3ResolutionPolicy,
    *,
    bucket_ids: "np.ndarray",
    dp_rank: int,
    dp_size: int,
    micro_batch_size: int,
    num_micro_batch: int,
    seed: int,
    schedule_fn: Callable[[int, int], int],
) -> BucketBatchSampler:
    """Construct a :class:`BucketBatchSampler` for this policy.

    The ``insufficient_bucket_policy`` is taken from the policy config so that
    the sampler and any downstream ``scheduler.restrict_to`` invocation stay in
    sync with the operator's declared expectation.
    """
    return BucketBatchSampler(
        bucket_ids=bucket_ids,
        all_bucket_ids=policy.all_bucket_ids,
        dp_rank=dp_rank,
        dp_size=dp_size,
        micro_batch_size=micro_batch_size,
        num_micro_batch=num_micro_batch,
        seed=seed,
        schedule_fn=schedule_fn,
        bucket_labels=policy.bucket_labels,
        insufficient_bucket_policy=policy.config.insufficient_bucket_policy,
    )


__all__ = [
    "RESOLUTION_POLICY_PRESET",
    "HunyuanImage3ResolutionPolicy",
    "ResolutionAnchorConfig",
    "ResolutionBucket",
    "ResolutionPolicyConfig",
    "build_hunyuan_image_3_bucket_batch_sampler",
    "build_hunyuan_image_3_bucket_indexer",
    "build_hunyuan_image_3_bucket_scheduler",
    "build_resolution_policy",
]
