name: device-api-check

# No need to avoid / cancel lightweight device api check job
on:
  pull_request:
  push:
    branches:
      - main

# Declare permissions just read content.
permissions:
  contents: read

jobs:
  device-api-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: .
      - uses: actions/setup-python@v3
      - name: Run device api usage normativity in VeOmni/tasks
        run: |
          python tests/special_senity/check_device_api_usage.py -d tasks
      - name: Run device api usage normativity in VeOmni/veomni
        run: |
          python tests/special_senity/check_device_api_usage.py -d veomni
